class RowEnvCtrl(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2017-06-03 03:41:03 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 53
        self.input_vars = ['env1']

    def move(self, env1):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['loc', 'stage']
        """
        output = dict()
        if self.state == 0:
            if (env1 == 1):
                self.state = 45

                output["loc"] = 2
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 1:
            if (env1 == 1):
                self.state = 45

                output["loc"] = 2
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 2:
            if (env1 == 3):
                self.state = 40

                output["loc"] = 12
                output["stage"] = 0
            elif (env1 == 1):
                self.state = 41

                output["loc"] = 8
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 3:
            if (env1 == 1):
                self.state = 41

                output["loc"] = 8
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 4:
            if (env1 == 3):
                self.state = 30

                output["loc"] = 16
                output["stage"] = 2
            else:
                self._error(env1)
        elif self.state == 5:
            if (env1 == 2):
                self.state = 32

                output["loc"] = 17
                output["stage"] = 2
            elif (env1 == 4):
                self.state = 4

                output["loc"] = 17
                output["stage"] = 2
            else:
                self._error(env1)
        elif self.state == 6:
            if (env1 == 1):
                self.state = 34

                output["loc"] = 18
                output["stage"] = 1
            elif (env1 == 3):
                self.state = 5

                output["loc"] = 18
                output["stage"] = 1
            else:
                self._error(env1)
        elif self.state == 7:
            if (env1 == 3):
                self.state = 5

                output["loc"] = 18
                output["stage"] = 1
            else:
                self._error(env1)
        elif self.state == 8:
            if (env1 == 2):
                self.state = 6

                output["loc"] = 17
                output["stage"] = 1
            elif (env1 == 4):
                self.state = 7

                output["loc"] = 17
                output["stage"] = 1
            else:
                self._error(env1)
        elif self.state == 9:
            if (env1 == 1):
                self.state = 27

                output["loc"] = 16
                output["stage"] = 4
            else:
                self._error(env1)
        elif self.state == 10:
            if (env1 == 1):
                self.state = 27

                output["loc"] = 16
                output["stage"] = 4
            else:
                self._error(env1)
        elif self.state == 11:
            if (env1 == 1):
                self.state = 15

                output["loc"] = 20
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 12:
            if (env1 == 3):
                self.state = 22

                output["loc"] = 16
                output["stage"] = 0
            elif (env1 == 1):
                self.state = 23

                output["loc"] = 16
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 13:
            if (env1 == 3):
                self.state = 22

                output["loc"] = 16
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 14:
            if (env1 == 2):
                self.state = 12

                output["loc"] = 15
                output["stage"] = 0
            elif (env1 == 4):
                self.state = 13

                output["loc"] = 21
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 15:
            if (env1 == 2):
                self.state = 16

                output["loc"] = 20
                output["stage"] = 0
            elif (env1 == 0):
                self.state = 11

                output["loc"] = 20
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 16:
            if (env1 == 3):
                self.state = 14

                output["loc"] = 20
                output["stage"] = 0
            elif (env1 == 1):
                self.state = 15

                output["loc"] = 20
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 17:
            if (env1 == 3):
                self.state = 22

                output["loc"] = 16
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 18:
            if (env1 == 2):
                self.state = 16

                output["loc"] = 20
                output["stage"] = 0
            elif (env1 == 4):
                self.state = 17

                output["loc"] = 16
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 19:
            if (env1 == 1):
                self.state = 23

                output["loc"] = 16
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 20:
            if (env1 == 3):
                self.state = 40

                output["loc"] = 12
                output["stage"] = 0
            elif (env1 == 1):
                self.state = 23

                output["loc"] = 16
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 21:
            if (env1 == 3):
                self.state = 40

                output["loc"] = 12
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 22:
            if (env1 == 2):
                self.state = 20

                output["loc"] = 17
                output["stage"] = 0
            elif (env1 == 4):
                self.state = 21

                output["loc"] = 17
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 23:
            if (env1 == 0):
                self.state = 19

                output["loc"] = 17
                output["stage"] = 0
            elif (env1 == 2):
                self.state = 20

                output["loc"] = 17
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 24:
            if (env1 == 3):
                self.state = 22

                output["loc"] = 16
                output["stage"] = 0
            elif (env1 == 1):
                self.state = 23

                output["loc"] = 16
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 25:
            if (env1 == 3):
                self.state = 18

                output["loc"] = 15
                output["stage"] = 4
            else:
                self._error(env1)
        elif self.state == 26:
            if (env1 == 2):
                self.state = 24

                output["loc"] = 15
                output["stage"] = 4
            elif (env1 == 4):
                self.state = 25

                output["loc"] = 16
                output["stage"] = 4
            else:
                self._error(env1)
        elif self.state == 27:
            if (env1 == 2):
                self.state = 24

                output["loc"] = 15
                output["stage"] = 4
            elif (env1 == 0):
                self.state = 10

                output["loc"] = 17
                output["stage"] = 4
            else:
                self._error(env1)
        elif self.state == 28:
            if (env1 == 3):
                self.state = 26

                output["loc"] = 16
                output["stage"] = 4
            elif (env1 == 1):
                self.state = 27

                output["loc"] = 16
                output["stage"] = 4
            else:
                self._error(env1)
        elif self.state == 29:
            if (env1 == 3):
                self.state = 26

                output["loc"] = 16
                output["stage"] = 4
            else:
                self._error(env1)
        elif self.state == 30:
            if (env1 == 2):
                self.state = 28

                output["loc"] = 17
                output["stage"] = 3
            elif (env1 == 4):
                self.state = 29

                output["loc"] = 17
                output["stage"] = 3
            else:
                self._error(env1)
        elif self.state == 31:
            if (env1 == 0):
                self.state = 9

                output["loc"] = 17
                output["stage"] = 3
            elif (env1 == 2):
                self.state = 28

                output["loc"] = 17
                output["stage"] = 3
            else:
                self._error(env1)
        elif self.state == 32:
            if (env1 == 3):
                self.state = 30

                output["loc"] = 16
                output["stage"] = 2
            elif (env1 == 1):
                self.state = 31

                output["loc"] = 16
                output["stage"] = 2
            else:
                self._error(env1)
        elif self.state == 33:
            if (env1 == 1):
                self.state = 31

                output["loc"] = 16
                output["stage"] = 2
            else:
                self._error(env1)
        elif self.state == 34:
            if (env1 == 2):
                self.state = 32

                output["loc"] = 17
                output["stage"] = 2
            elif (env1 == 0):
                self.state = 33

                output["loc"] = 17
                output["stage"] = 2
            else:
                self._error(env1)
        elif self.state == 35:
            if (env1 == 1):
                self.state = 34

                output["loc"] = 18
                output["stage"] = 1
            else:
                self._error(env1)
        elif self.state == 36:
            if (env1 == 2):
                self.state = 38

                output["loc"] = 12
                output["stage"] = 1
            elif (env1 == 4):
                self.state = 39

                output["loc"] = 11
                output["stage"] = 1
            else:
                self._error(env1)
        elif self.state == 37:
            if (env1 == 0):
                self.state = 35

                output["loc"] = 13
                output["stage"] = 1
            elif (env1 == 2):
                self.state = 38

                output["loc"] = 12
                output["stage"] = 1
            else:
                self._error(env1)
        elif self.state == 38:
            if (env1 == 3):
                self.state = 36

                output["loc"] = 12
                output["stage"] = 1
            elif (env1 == 1):
                self.state = 37

                output["loc"] = 12
                output["stage"] = 1
            else:
                self._error(env1)
        elif self.state == 39:
            if (env1 == 3):
                self.state = 8

                output["loc"] = 16
                output["stage"] = 1
            else:
                self._error(env1)
        elif self.state == 40:
            if (env1 == 2):
                self.state = 38

                output["loc"] = 12
                output["stage"] = 1
            elif (env1 == 4):
                self.state = 39

                output["loc"] = 11
                output["stage"] = 1
            else:
                self._error(env1)
        elif self.state == 41:
            if (env1 == 2):
                self.state = 2

                output["loc"] = 13
                output["stage"] = 0
            elif (env1 == 0):
                self.state = 3

                output["loc"] = 8
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 42:
            if (env1 == 3):
                self.state = 40

                output["loc"] = 12
                output["stage"] = 0
            elif (env1 == 1):
                self.state = 41

                output["loc"] = 8
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 43:
            if (env1 == 3):
                self.state = 40

                output["loc"] = 12
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 44:
            if (env1 == 2):
                self.state = 42

                output["loc"] = 7
                output["stage"] = 0
            elif (env1 == 4):
                self.state = 43

                output["loc"] = 7
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 45:
            if (env1 == 0):
                self.state = 1

                output["loc"] = 2
                output["stage"] = 0
            elif (env1 == 2):
                self.state = 42

                output["loc"] = 7
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 46:
            if (env1 == 3):
                self.state = 44

                output["loc"] = 2
                output["stage"] = 0
            elif (env1 == 1):
                self.state = 45

                output["loc"] = 2
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 47:
            if (env1 == 3):
                self.state = 44

                output["loc"] = 2
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 48:
            if (env1 == 1):
                self.state = 51

                output["loc"] = 0
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 49:
            if (env1 == 3):
                self.state = 52

                output["loc"] = 0
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 50:
            if (env1 == 1):
                self.state = 51

                output["loc"] = 0
                output["stage"] = 0
            elif (env1 == 3):
                self.state = 52

                output["loc"] = 0
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 51:
            if (env1 == 0):
                self.state = 0

                output["loc"] = 1
                output["stage"] = 0
            elif (env1 == 2):
                self.state = 46

                output["loc"] = 1
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 52:
            if (env1 == 2):
                self.state = 46

                output["loc"] = 1
                output["stage"] = 0
            elif (env1 == 4):
                self.state = 47

                output["loc"] = 1
                output["stage"] = 0
            else:
                self._error(env1)
        elif self.state == 53:
            if (env1 == 0):
                self.state = 0

                output["loc"] = 1
                output["stage"] = 0
            elif (env1 == 0):
                self.state = 1

                output["loc"] = 2
                output["stage"] = 0
            elif (env1 == 2):
                self.state = 2

                output["loc"] = 13
                output["stage"] = 0
            elif (env1 == 0):
                self.state = 3

                output["loc"] = 8
                output["stage"] = 0
            elif (env1 == 0):
                self.state = 11

                output["loc"] = 20
                output["stage"] = 0
            elif (env1 == 2):
                self.state = 12

                output["loc"] = 15
                output["stage"] = 0
            elif (env1 == 4):
                self.state = 13

                output["loc"] = 21
                output["stage"] = 0
            elif (env1 == 3):
                self.state = 14

                output["loc"] = 20
                output["stage"] = 0
            elif (env1 == 1):
                self.state = 15

                output["loc"] = 20
                output["stage"] = 0
            elif (env1 == 2):
                self.state = 16

                output["loc"] = 20
                output["stage"] = 0
            elif (env1 == 4):
                self.state = 17

                output["loc"] = 16
                output["stage"] = 0
            elif (env1 == 0):
                self.state = 19

                output["loc"] = 17
                output["stage"] = 0
            elif (env1 == 2):
                self.state = 20

                output["loc"] = 17
                output["stage"] = 0
            elif (env1 == 4):
                self.state = 21

                output["loc"] = 17
                output["stage"] = 0
            elif (env1 == 3):
                self.state = 22

                output["loc"] = 16
                output["stage"] = 0
            elif (env1 == 1):
                self.state = 23

                output["loc"] = 16
                output["stage"] = 0
            elif (env1 == 3):
                self.state = 40

                output["loc"] = 12
                output["stage"] = 0
            elif (env1 == 1):
                self.state = 41

                output["loc"] = 8
                output["stage"] = 0
            elif (env1 == 2):
                self.state = 42

                output["loc"] = 7
                output["stage"] = 0
            elif (env1 == 4):
                self.state = 43

                output["loc"] = 7
                output["stage"] = 0
            elif (env1 == 3):
                self.state = 44

                output["loc"] = 2
                output["stage"] = 0
            elif (env1 == 1):
                self.state = 45

                output["loc"] = 2
                output["stage"] = 0
            elif (env1 == 2):
                self.state = 46

                output["loc"] = 1
                output["stage"] = 0
            elif (env1 == 4):
                self.state = 47

                output["loc"] = 1
                output["stage"] = 0
            elif (env1 == 0):
                self.state = 48

                output["loc"] = 0
                output["stage"] = 0
            elif (env1 == 4):
                self.state = 49

                output["loc"] = 0
                output["stage"] = 0
            elif (env1 == 2):
                self.state = 50

                output["loc"] = 0
                output["stage"] = 0
            elif (env1 == 1):
                self.state = 51

                output["loc"] = 0
                output["stage"] = 0
            elif (env1 == 3):
                self.state = 52

                output["loc"] = 0
                output["stage"] = 0
            else:
                self._error(env1)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, env1):
        raise ValueError("Unrecognized input: " + (
            "env1 = {env1}; ").format(
                env1=env1))
